### ISSUE TITLE
Error deploying to Netlify after Tailwind 3.3.0 update

### ISSUE THREAD

**Issue by nddr** [nuxt-modules/tailwindcss#652]
### Version
@nuxtjs/tailwindcss: 6.6.4
nuxt: 3.3.2

### Steps to reproduce
1. Run `npm upgrade`
2. Deploy changes

### What is Expected?
Successful deployment

### What is actually happening?
Failed deployment

`[error] Cannot find module '/opt/build/repo/node_modules/tailwindcss/stubs/simpleConfig.stub.js' imported from /opt/build/repo/node_modules/@nuxtjs/tailwindcss/dist/module.mjs`

**Comment by vinoddotcom** [comment]
In my case on updating, @nuxt:3.3.2 `=>` @nuxt:3.3.3 sane issue find.

**Comment by bjerggaard** [comment]
I'm having the same issue when building after upgrading tailwindcss to 3.3.0 and @nuxtjs/tailwindcss to 6.6.4.

 ERROR  Cannot start nuxt:  Cannot find module 'C:\Repos\app\node_modules\tailwindcss\stubs\simpleConfig.stub.js' imported from C:\Repos\app\node_modules\@nuxtjs\tailwindcss\dist\module.mjs

**Comment by rpv88** [comment]
I had the same error, but a new release has been uploaded. Version 6.6.5 should fix it!

**Comment by ineshbose** [comment]
Closing! 😄
